### ISSUE TITLE
op.sync_enum_values does not work on columns that have constraints

### ISSUE THREAD

**Issue by RustyGuard** [Pogchamp-company/alembic-postgresql-enum#11]
Possible solution: https://stackoverflow.com/questions/53257926/add-remove-a-value-of-postgresql-enum-type-in-alembic

**Comment by A-Nancio** [comment]
After using this lib in my own project, this issue occurred again, when attempting to update an enum used by a column that has a foreign key constraint, when running the migration.

The error code is the following (with tables names obscured):
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) foreign key constraint "fk_<table_name>_<enum>_id" cannot be implemented
DETAIL:  Key columns "<enum>_id" and "id" are of incompatible types: type_<enum> and type_<enum>_old.

[SQL: ALTER TABLE public.<table_name> ALTER COLUMN <enum>_id TYPE public.type_<enum>
                    USING <enum>_id::text::public.type_<enum>;
                    ]
(Background on this error at: https://sqlalche.me/e/20/f405)

```

**Comment by RustyGuard** [comment]
@A-Nancio please provide the fk constraint. May be there is another operator that I need to add

**Comment by A-Nancio** [comment]
Surely:

```python
@declared_mixin
class <Enum>_Mixin:
    @declared_attr
    def <enum>_id(cls) -> Mapped [Enum | None]:
        return mapped_column(ForeignKey("<enum>.id"), index=True)
    
@declared_attr
    def <enum>(cls) -> Mapped[Enum | None]:
        return relationship("<enum_table>")
```

**Comment by RustyGuard** [comment]
As I can see you are using non-native postgresql enum.
Alembic has no issues when dealing with tables. It is likely that you have problems on your side

**Comment by A-Nancio** [comment]
I see, thank you for the feedback, I'll look further into it
