### ISSUE TITLE
Enums are not generated inside ARRAY

### ISSUE THREAD

**Issue by polamayster** [Pogchamp-company/alembic-postgresql-enum#12]
Unfortunately approach does not work with neither sa.types.ARRAY nor postgresql.ARRAY for cases like: Column(types.ARRAY(Enum(Goal, name="goal_enum"))) as currently it fails to generate enums definition in such cases.

**Comment by RustyGuard** [comment]
There is already a [pull request](https://github.com/Pogchamp-company/alembic-postgresql-enum/pulls) working on that

**Comment by RustyGuard** [comment]
Changes will be available in next 0.1.6 release
