### ISSUE TITLE
Problems detecting enums when dealing with non-standard schema

### ISSUE THREAD

**Issue by LordPhwa** [Pogchamp-company/alembic-postgresql-enum#26]
When trying to autogenerate a revision with a non-default schema, an unchanged enum is not correctly detected, and a create/drop pair is generated. 

I have included detailed steps to reproduce the issue, if there is anything missing or unclear i will gladly assist.

Also thanks a lot for this project!

## Expected Behavior

No changes to enum types or other columns should be issued.

## Current Behavior

A pair of create and drop operations, as well as alter_column statements is generated, see below for details

### Try No. 1

```python
# Definition of my model
import enum
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import mapped_column, Mapped
from sqlalchemy.dialects.postgresql import ENUM

my_metadata = MetaData(schema="my_schema")

class Base(DeclarativeBase):
    metadata = my_metadata


# Definition of my enum
class TestStatus(enum.Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"

# Definition of my model class
class Test(Base):

    __tablename__ = "test"

    status: Mapped[TestStatus] = mapped_column(
        ENUM(TestStatus, name="test_status"),
        nullable=False,
    )
```

```python
# Inside env.py
import alembic_postgresql_enum

...

from app.model import Base
target_metadata = Base.metadata

...

with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table_schema=target_metadata.schema,
            include_schemas=True,
        )

        with context.begin_transaction():
            context.run_migrations()
```

```python
# it seems it wants to create the enum type without specifying a schema - therefore creating in 'public'
sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='test_status').create(op.get_bind())

...

# example of alter_column statement for a model that uses this enum
# existing type is detected as member of my_schema, but new type lacks the schema specifier
op.alter_column('test', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='test_status', schema='my_schema'),
               type_=        postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='test_status'),
               existing_nullable=False,
               schema='my_schema')

...

# at the end it tries to drop the existing enum from my_schema
sa.Enum('FAILED', 'SUCCESS', 'PENDING', name='my_schema.test_status', schema='my_schema').drop(op.get_bind())

```

### Try No. 2

I explicitly specified the schema whenever i used the enum as column type.

```python
# Definition of my model
import enum
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import mapped_column, Mapped
from sqlalchemy.dialects.postgresql import ENUM

my_metadata = MetaData(schema="my_schema")

class Base(DeclarativeBase):
    metadata = my_metadata


# Definition of my enum
class TestStatus(enum.Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"

# Definition of my model class
class Test(Base):

    __tablename__ = "test"

    status: Mapped[TestStatus] = mapped_column(
        ENUM(TestStatus, name="test_status", schema=Base.metadata.schema),  # <--- This changed
        nullable=False,
    )
```

```python
# Inside env.py (unchanged from previous version)
import alembic_postgresql_enum

...

from app.model import Base
target_metadata = Base.metadata

...

with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table_schema=target_metadata.schema,
            include_schemas=True,
        )

        with context.begin_transaction():
            context.run_migrations()
```

```python
# Now it wants to create the enum type with the schema specifier
sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='test_status', schema='my_schema').create(op.get_bind())

...

# NO alter_column statement is generated

...
# Now it wants to drop the enum
sa.Enum('FAILED', 'SUCCESS', 'PENDING', name='my_schema.test_status', schema='my_schema').drop(op.get_bind())

```

Issuing the second version then leads to

```
sqlalchemy.exc.ProgrammingError: (psycopg.errors.DuplicateObject) type "test_status" already exists
```

## Context (Environment)
I am using 
- alembic-postgresql-enum 0.1.8
- sqlalchemy 2.0.20
- alembic 1.12.0

**Comment by RustyGuard** [comment]
Try No. 2 will be tested and fixed shortly

**Comment by RustyGuard** [comment]
In No. 1 seems like alembic considers table metadata as default enum metadata, library should do it also

**Comment by RustyGuard** [comment]
No. 2 is fixed, will be shipped with next patch update

**Comment by RustyGuard** [comment]
No. 1 is working as intended. `sqlalchemy.Enum` `inherit_schema` parameter is set to `False` by default so TestStatus schema is `public`.

**Comment by RustyGuard** [comment]
> No. 2 is fixed, will be shipped with next patch update

For now there is 0.1.9a1 version containing fix

**Comment by RustyGuard** [comment]
> I am not sure about this, but i can imagine there being another mechanism at work for the decision which schema the enum belongs to in sqlalchemy.
> 
> [SQLAlchemy Documentation](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum.params.schema) clearly states that the default for `inherit_schema` is `false`, but when the schema is created initially via `Base.metadata.create_all(engine)`, the `inherit_schema` parameter is also not specified anywhere for the enum types, but the enum type is created in `my_schema`, and there is nothing inside `public`

I tried to reproduce this with tests in 1.4 style and everything worked fine. But when mapped_column was used everything everything went as you told.

**Comment by RustyGuard** [comment]
> I am not sure about this, but i can imagine there being another mechanism at work for the decision which schema the enum belongs to in sqlalchemy.
> 
> [SQLAlchemy Documentation](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum.params.schema) clearly states that the default for `inherit_schema` is `false`, but when the schema is created initially via `Base.metadata.create_all(engine)`, the `inherit_schema` parameter is also not specified anywhere for the enum types, but the enum type is created in `my_schema`, and there is nothing inside `public`

I wrote tests that replicate No. 1. Results show that enum is correctly created within `public` schema

**Comment by RustyGuard** [comment]
Our library does not modify behavior of `op.alter_column` so issue is caused by alembic

**Comment by RustyGuard** [comment]
> Do you think i should open an issue with alembic for this behavior, or is it just an usage error on my behalf?

I am not sure. I have not worked with `search_path`
