### ISSUE TITLE
Automatically add USING statement when altering column to use enum

### ISSUE THREAD

**Issue by skylerberg** [Pogchamp-company/alembic-postgresql-enum#43]
First  off, thanks for this nifty utility library! It fixes a few pain points with alembic and posgresql.

One existing pain point is altering a column's data type into an enum type. When changing a TEXT column into an ENUM column, the text value is not automatically cast to the enum value. To manually force the casting, you must include a postgresql specific USING statement. Alembic does not generate this, so the auto-generated migration will fail.

We could fix this by detecting when a column is being changed into an enum column and then adding the [postgresql_using](https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column.params.postgresql_using) argument to the alter column operation. The string should be `<column_name>::<enum_name>`.

Not sure if this is in scope for this library but thought it was more likely to get fixed here than in alembic itself because it is such a niche use-case.

**Comment by RustyGuard** [comment]
Such a usecase was in the [warehouse](https://github.com/pypi/warehouse/blob/main/warehouse/migrations/versions/70f918653fc6_fix_up_enums.py). Our library will deal with that.

**Comment by skylerberg** [comment]
Incredibly fast turnaround on this. Awesome work and thanks again for the library!
