### ISSUE TITLE
Missing py.typed to indicate native typing support

### ISSUE THREAD

**Issue by bartelemi** [Pogchamp-company/alembic-postgresql-enum#66]
## what.
Since you're declaring types in your codebase, you should add the `py.typed` file to the repository (under the `alembic_postgresql_enum` directory) and include it in the distributed package.

This is so that people don't have to add your library to mypy ignore list :)

## references.
https://peps.python.org/pep-0561/#packaging-type-information

**Comment by RustyGuard** [comment]
Thank you for suggestion however I do not think it is necessary. Our library is only imported in env.py file which is rarely checked by mypy (correct me if I am wrong)

**Comment by bfontaine** [comment]
> Our library is only imported in env.py file which is rarely checked by mypy (correct me if I am wrong)

Well, mypy checks whatever you ask it to check. I prefer to check everything I can, and without this `py.typed` I get a warning on this library. It’s not super important, but if you could add it in the next release it would be nice :)

**Comment by bartelemi** [comment]
> > Our library is only imported in env.py file which is rarely checked by mypy (correct me if I am wrong)
> 
> Well, mypy checks whatever you ask it to check. I prefer to check everything I can, and without this `py.typed` I get a warning on this library. It’s not super important, but if you could add it in the next release it would be nice :)

Pretty much this ☝🏻 Without the _py.typed_ file (which is just an empty file in your repo, an indicator), I have to explicitly add this library in the mypy exclude list. It looks like you already add type definitions to your lib, so the only thing to worry about is adding this file and making sure it is shipped in the final package.

![image](https://github.com/Pogchamp-company/alembic-postgresql-enum/assets/6844101/a94e3742-e5f7-4393-a032-69a76a18a8cd)

**Comment by RustyGuard** [comment]
These changes are shipped in `1.2.0a1` version. I'll close this issue when next release will be dropped
