### ISSUE TITLE
Mypy errors when generating migration

### ISSUE THREAD

**Issue by 4c0n** [Pogchamp-company/alembic-postgresql-enum#80]
Generating the migration goes well and executing works like a charm, however mypy has a few complaints:

```sh
migrations/versions/cd7033b17112_update_form_component_types_enum.py:13: error: Module "alembic_postgresql_enum" does not explicitly export attribute "TableReference"  [attr-defined]
migrations/versions/cd7033b17112_update_form_component_types_enum.py:26: error: Module has no attribute "sync_enum_values"  [attr-defined]
migrations/versions/cd7033b17112_update_form_component_types_enum.py:44: error: Module has no attribute "sync_enum_values"  [attr-defined]
```

I'm running mypy in strict mode btw. I suppose the first one could be fixed easily by either defining `__all__`  in the `__init__.py` or by using:
```python
from .get_enum_data import ColumnType as ColumnType
from .get_enum_data import TableReference as TableReference
```

instead of:
```python
from .get_enum_data import ColumnType, TableReference
```

Not sure how to go about fixing the others though.

**Comment by 4c0n** [comment]
Hi guys, I saw your PR where you seem to allow ignoring type errors?
Could you explain how this solves the issue? At least in part it is possible to solve the issue by using the suggestion above, so I don't really understand the ignore solution and how I can get rid of the errors that are already there right now.

**Comment by RustyGuard** [comment]
https://github.com/Pogchamp-company/alembic-postgresql-enum?tab=readme-ov-file#configuration

You can now configure our library to add type ignore automatically
