### ISSUE TITLE
Use same schema as table or support specifying enum schema?

### ISSUE THREAD

**Issue by pikevsten** [Pogchamp-company/alembic-postgresql-enum#82]
Auto-generation puts the enums in the `public` schema, even if the table is in a different schema.

How can I change the schema that auto-generation compares against?

**Comment by RustyGuard** [comment]
You can explicitly specify schema on your enum object like that `sa.Enum(..., schema="your_schema")`

**Comment by pikevsten** [comment]
Thank you ❤️
