### ISSUE TITLE
Specific schema name

### ISSUE THREAD

**Issue by PavukEdya** [Pogchamp-company/alembic-postgresql-enum#86]
i know i can set them in revision but it doesn't look comfortably
maybe create  Enum attribute (__schema__ f.e. ) which was used to generate revision

**Comment by RustyGuard** [comment]
https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum.__init__
Enum already has `schema` attribute, which correctly works with our extension

**Comment by PavukEdya** [comment]
thanks
