### ISSUE TITLE
Ability to use `include_name` from alembic context

### ISSUE THREAD

**Issue by amithkk** [Pogchamp-company/alembic-postgresql-enum#89]
Sometimes, there are `enum`s in the schema that need to be ignored or which are controlled by other applications.

To address this, [alembic has a feature to pass in `include_name`](https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure.params.include_name), where you can pass a function that determines whether change detection will consider the object for migration generation.

However, alembic-postgresql-enum does not use this function before calculating changes. If this were implemented, you could do something along the lines of:

```python
def include_name(name, type_, parent_names):
    if type_ == "enum":
        return name not in ["exclude_enum_1", "exclude_enum_2"]
    else:
        return True

context.configure(
    # ...
    include_name = include_name
)
```

**Comment by dswistowski** [comment]
@amithkk  I literally today needed such feature, and added it in my form 🤣  https://github.com/Pogchamp-company/alembic-postgresql-enum/pull/90

**Comment by RustyGuard** [comment]
This feature became a part of 1.5.0 release :tada:
